-- create database db_ecomm
-- use db_ecomm;
-- create table tb_produtos(
	-- id bigint auto_increment,
    -- nomeproduto varchar (500),
    -- marca varchar (100),
    -- valor float,
    -- disponibilidade boolean,
    
    -- primary key (id) )
 -- select * from tb_produtos
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Meia Atleta", "Adidas", 39.00, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Tênis", "Adidas", 900.00, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Tênis", "Adidas",750.90, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Chuteira", "Adidas", 250.40, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Meia Atleta", "Nike", 29.99, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Tênis", "Nike", 850.99, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Chuteira", "Nike", 750.80, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Chuteira Infantil", "Nike", 150.30, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Camisa Esportiva", "Adidas", 120.00, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Camisa Esportiva", "Nike", 120.00, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Mala Viagem Esportiva", "Adidas", 850.00, true);
-- insert into tb_produtos(nomeproduto, marca, valor, disponibilidade) value ("Mala Viagem Esportiva", "Nike", 860.00, true);
-- select * from tb_produtos
-- select * from tb_produtos where valor > 500
-- select * from tb_produtos where valor < 500
-- select * from tb_produtos where valor >= 700 && valor <= 900
-- delete from tb_produtos where id = 12
-- select * from tb_produtos
-- update tb_produtos set marca = "Umbro" where id = 11;
-- select * from tb_produtos